/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.35
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  GlobalCustomerGetEndpointV1Response,
} from './models';

/**
 * globalCustomerGetEndpointV1 - parameters interface
 */
export interface IGlobalCustomerGetEndpointV1Params {
  pksCustomerCode: string;
  sInfrastructureproductCode?: 'appcluster01' | 'ezsignuser';
}

/**
 * GlobalCustomerApi - API class
 */
@autoinject()
export class GlobalCustomerApi extends Api {

  /**
   * Creates a new GlobalCustomerApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Get customer endpoint
   * Retrieve the customer\&#39;s specific server endpoint where to send requests. This will help locate the proper region (ie: sInfrastructureregionCode) and the proper environment (ie: sInfrastructureenvironmenttypeDescription) where the customer\&#39;s data is stored.
   * @param params.pksCustomerCode The customer code assigned to your account
   * @param params.sInfrastructureproductCode The infrastructure product Code  If undefined, \&quot;appcluster01\&quot; is assumed
   */
  async globalCustomerGetEndpointV1(params: IGlobalCustomerGetEndpointV1Params): Promise<GlobalCustomerGetEndpointV1Response> {
    // Verify required parameters are set
    this.ensureParamIsSet('globalCustomerGetEndpointV1', params, 'pksCustomerCode');

    // Create URL to call
    const url = `${this.basePath}/1/customer/{pksCustomerCode}/endpoint`
      .replace(`{${'pksCustomerCode'}}`, encodeURIComponent(`${params['pksCustomerCode']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()
      // Set query parameters
      .withParams({ 
        'sInfrastructureproductCode': params['sInfrastructureproductCode'],
      })

      // Authentication 'Authorization' required
      .withHeader('Authorization', this.authStorage.getAuthorization())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

