/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
} from './models';

/**
 * ssprRemindUsernamesV1 - parameters interface
 */
export interface ISsprRemindUsernamesV1Params {
}

/**
 * ModuleSsprApi - API class
 */
@autoinject()
export class ModuleSsprApi extends Api {

  /**
   * Creates a new ModuleSsprApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Remind of forgotten username(s)
   * This endpoint returns an email with the username(s) matching the email address provided in case of forgotten username
   */
  async ssprRemindUsernamesV1(): Promise<any> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/1/module/sspr/remindUsernames`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()

      // Authentication 'Authorization' required
      .withHeader('Authorization', this.authStorage.getAuthorization())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

