/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.33
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  EzsignfolderGetObjectV1Response,
  EzsignfolderDeleteObjectV1Response,
  EzsignfolderSendV1Request,
  EzsignfolderCreateObjectV1Response,
  EzsignfolderSendV1Response,
} from './models';

/**
 * ezsignfolderCreateObjectV1 - parameters interface
 */
export interface IEzsignfolderCreateObjectV1Params {
  ezsignfolderCreateObjectV1Request: Array<EzsignfolderCreateObjectV1Request>;
}

/**
 * ezsignfolderDeleteObjectV1 - parameters interface
 */
export interface IEzsignfolderDeleteObjectV1Params {
  pkiEzsignfolderID: number;
}

/**
 * ezsignfolderGetChildrenV1 - parameters interface
 */
export interface IEzsignfolderGetChildrenV1Params {
  pkiEzsignfolderID: number;
}

/**
 * ezsignfolderGetObjectV1 - parameters interface
 */
export interface IEzsignfolderGetObjectV1Params {
  pkiEzsignfolderID: number;
}

/**
 * ezsignfolderSendV1 - parameters interface
 */
export interface IEzsignfolderSendV1Params {
  pkiEzsignfolderID: number;
  ezsignfolderSendV1Request: EzsignfolderSendV1Request;
}

/**
 * ObjectEzsignfolderApi - API class
 */
@autoinject()
export class ObjectEzsignfolderApi extends Api {

  /**
   * Creates a new ObjectEzsignfolderApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Create a new Ezsignfolder
   * The endpoint allows to create one or many elements at once.  The array can contain simple (Just the object) or compound (The object and its child) objects.  Creating compound elements allows to reduce the multiple requests to create all child objects.
   * @param params.ezsignfolderCreateObjectV1Request 
   */
  async ezsignfolderCreateObjectV1(params: IEzsignfolderCreateObjectV1Params): Promise<EzsignfolderCreateObjectV1Response> {
    // Verify required parameters are set
    this.ensureParamIsSet('ezsignfolderCreateObjectV1', params, 'ezsignfolderCreateObjectV1Request');

    // Create URL to call
    const url = `${this.basePath}/1/object/ezsignfolder`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['ezsignfolderCreateObjectV1Request'] || {}))

      // Authentication 'Authorization' required
      .withHeader('Authorization', this.authStorage.getAuthorization())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Delete an existing Ezsignfolder
   * @param params.pkiEzsignfolderID The unique ID of the Ezsignfolder
   */
  async ezsignfolderDeleteObjectV1(params: IEzsignfolderDeleteObjectV1Params): Promise<EzsignfolderDeleteObjectV1Response> {
    // Verify required parameters are set
    this.ensureParamIsSet('ezsignfolderDeleteObjectV1', params, 'pkiEzsignfolderID');

    // Create URL to call
    const url = `${this.basePath}/1/object/ezsignfolder/{pkiEzsignfolderID}`
      .replace(`{${'pkiEzsignfolderID'}}`, encodeURIComponent(`${params['pkiEzsignfolderID']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asDelete()

      // Authentication 'Authorization' required
      .withHeader('Authorization', this.authStorage.getAuthorization())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Retrieve an existing Ezsignfolder\&#39;s children IDs
   * @param params.pkiEzsignfolderID The unique ID of the Ezsignfolder
   */
  async ezsignfolderGetChildrenV1(params: IEzsignfolderGetChildrenV1Params): Promise<any> {
    // Verify required parameters are set
    this.ensureParamIsSet('ezsignfolderGetChildrenV1', params, 'pkiEzsignfolderID');

    // Create URL to call
    const url = `${this.basePath}/1/object/ezsignfolder/{pkiEzsignfolderID}/getChildren`
      .replace(`{${'pkiEzsignfolderID'}}`, encodeURIComponent(`${params['pkiEzsignfolderID']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'Authorization' required
      .withHeader('Authorization', this.authStorage.getAuthorization())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Retrieve an existing Ezsignfolder
   * @param params.pkiEzsignfolderID The unique ID of the Ezsignfolder
   */
  async ezsignfolderGetObjectV1(params: IEzsignfolderGetObjectV1Params): Promise<EzsignfolderGetObjectV1Response> {
    // Verify required parameters are set
    this.ensureParamIsSet('ezsignfolderGetObjectV1', params, 'pkiEzsignfolderID');

    // Create URL to call
    const url = `${this.basePath}/1/object/ezsignfolder/{pkiEzsignfolderID}`
      .replace(`{${'pkiEzsignfolderID'}}`, encodeURIComponent(`${params['pkiEzsignfolderID']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'Authorization' required
      .withHeader('Authorization', this.authStorage.getAuthorization())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Send the Ezsignfolder to the signatories for signature
   * @param params.pkiEzsignfolderID The unique ID of the Ezsignfolder
   * @param params.ezsignfolderSendV1Request 
   */
  async ezsignfolderSendV1(params: IEzsignfolderSendV1Params): Promise<EzsignfolderSendV1Response> {
    // Verify required parameters are set
    this.ensureParamIsSet('ezsignfolderSendV1', params, 'pkiEzsignfolderID');
    this.ensureParamIsSet('ezsignfolderSendV1', params, 'ezsignfolderSendV1Request');

    // Create URL to call
    const url = `${this.basePath}/1/object/ezsignfolder/{pkiEzsignfolderID}/send`
      .replace(`{${'pkiEzsignfolderID'}}`, encodeURIComponent(`${params['pkiEzsignfolderID']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['ezsignfolderSendV1Request'] || {}))

      // Authentication 'Authorization' required
      .withHeader('Authorization', this.authStorage.getAuthorization())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

